name:                one-for-all
version:             0.1.0.0
github:              "sertel/one-for-all"
license:             BSD3
author:              "Sebastian Ertel"
maintainer:          "sebastian.ertel@gmail.com"
copyright:           "2018 Sebastian Ertel"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/sertel/one-for-all#readme>

dependencies:
- base >= 4.7 && < 5
- parsec
- syb
- template-haskell
- language-rust
- language-java
- prettyprinter
- text

default-extensions:
- FlexibleContexts
- FlexibleInstances
- TypeSynonymInstances
- LambdaCase
- TupleSections
- BangPatterns
- ExplicitForAll
- ScopedTypeVariables

library:
  source-dirs: src

# executables:
#   one-for-all-exe:
#     main:                Main.hs
#     source-dirs:         app
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - one-for-all

tests:
  one-for-all-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - one-for-all
    - hspec
